// Codes d'erreur stables : le front les traduit (i18n), jamais le `message`
// (français, pour les logs serveur uniquement). Un nouveau code ici doit avoir
// sa traduction dans frontend/src/i18n/locales/{fr,en}.json → errors.<CODE>.
export const ERROR_CODES = {
  AUTH_EMAIL_TAKEN: "AUTH_EMAIL_TAKEN",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_EMAIL_NOT_CONFIRMED: "AUTH_EMAIL_NOT_CONFIRMED",
  AUTH_ACCOUNT_SUSPENDED: "AUTH_ACCOUNT_SUSPENDED",
  AUTH_CONFIRM_TOKEN_INVALID: "AUTH_CONFIRM_TOKEN_INVALID",
  AUTH_RESET_TOKEN_INVALID: "AUTH_RESET_TOKEN_INVALID",
  AUTH_SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",
  AUTH_UNAUTHENTICATED: "AUTH_UNAUTHENTICATED",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  AUTH_CURRENT_PASSWORD_INCORRECT: "AUTH_CURRENT_PASSWORD_INCORRECT",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_GOOGLE_EMAIL_TAKEN: "AUTH_GOOGLE_EMAIL_TAKEN",
  AUTH_GOOGLE_EMAIL_UNVERIFIED: "AUTH_GOOGLE_EMAIL_UNVERIFIED",
  AUTH_GOOGLE_ALREADY_LINKED: "AUTH_GOOGLE_ALREADY_LINKED",
  AUTH_GOOGLE_NOT_CONFIGURED: "AUTH_GOOGLE_NOT_CONFIGURED",
  AUTH_NO_PASSWORD_SET: "AUTH_NO_PASSWORD_SET",
  AUTH_GOOGLE_UNLINK_REQUIRES_PASSWORD: "AUTH_GOOGLE_UNLINK_REQUIRES_PASSWORD",
  OAUTH_NOT_CONFIGURED: "OAUTH_NOT_CONFIGURED",
  OAUTH_STATE_INVALID: "OAUTH_STATE_INVALID",
  OAUTH_EXCHANGE_FAILED: "OAUTH_EXCHANGE_FAILED",
  SERVICE_UNKNOWN: "SERVICE_UNKNOWN",
  SERVICE_OAUTH_REQUIRED: "SERVICE_OAUTH_REQUIRED",
  SERVICE_CANNOT_UNSUBSCRIBE_DEFAULT: "SERVICE_CANNOT_UNSUBSCRIBE_DEFAULT",
  DASHBOARD_WIDGET_UNKNOWN: "DASHBOARD_WIDGET_UNKNOWN",
  DASHBOARD_CONFIG_INVALID: "DASHBOARD_CONFIG_INVALID",
  DASHBOARD_INSTANCE_NOT_FOUND: "DASHBOARD_INSTANCE_NOT_FOUND",
  DASHBOARD_ADAPTER_MISSING: "DASHBOARD_ADAPTER_MISSING",
  DASHBOARD_FETCH_FAILED: "DASHBOARD_FETCH_FAILED",
  ADMIN_USER_NOT_FOUND: "ADMIN_USER_NOT_FOUND",
  ADMIN_SELF_ROLE_CHANGE_FORBIDDEN: "ADMIN_SELF_ROLE_CHANGE_FORBIDDEN",
  ADMIN_SELF_DELETE_FORBIDDEN: "ADMIN_SELF_DELETE_FORBIDDEN",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export class HttpError extends Error {
  status: number;
  code: ErrorCode;
  constructor(status: number, code: ErrorCode, message?: string) {
    super(message ?? code);
    this.status = status;
    this.code = code;
  }
}

export function httpError(status: number, code: ErrorCode, message?: string): HttpError {
  return new HttpError(status, code, message);
}
